### ISSUE TITLE
Livneh 2015 climatalogic vars

### ISSUE THREAD

**Issue by jonschwenk** [VeinsOfTheEarth/rabpro#106]
### Title

Livneh 2015 precip, max/min temp

### Description

A data set of observed daily and monthly averaged precipitation, maximum and minimum temperature, gridded to a 1/16° (~6km) resolution that spans the entire country of Mexico, the conterminous U.S. (CONUS), and regions of Canada south of 53° N for the period 1950-2015. The dataset improves previous products in spatial extent, orographic precipitation adjustment over Mexico and parts of Canada, and reduction of transboundary discontinuities. The precipitation is adjusted for orographic effects using an elevation-aware 1981-2010 precipitation climatology. Because of the consistent gridding methodology, the current product reduces transboundary discontinuities making it suitable for estimating large-scale hydrometeorologic phenomena. Also included are daily wind data from the National Centers for Environmental Prediction - National Centers for Atmospheric Research (NCEP - NCAR) resampled to the same grid as temperature and precipitation.

Data are stored as a series of netCDF files; one per month but with daily data.

Each netCDF file contains the variables: `lon, lat, time, Prec, Tmax, Tmin,` and `wind`. 

Units: Prec: mm, Tmax/Tmin: C, wind: m/s. Time is given in days since 1900-01-01.

There are four places to acquire the data; see [here](https://climatedataguide.ucar.edu/climate-data/livneh-gridded-precipitation-and-other-meteorological-variables-continental-us-mexico).

### Citation

Livneh, B., T. J. Bohn, D. W. Pierce, F. Munoz-Arriola, B. Nijssen, R. Vose, D. R. Cayan, and L. Brekke, 2015: A spatially comprehensive, hydrometeorological data set for Mexico, the U.S., and Southern Canada 1950–2013. Scientific Data, 2, https://doi.org/10.1038/sdata.2015.42.

### Projection

4326

### Time start

1950-01-01

### Time end

2014-12-31

### URL

https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc%3A0129374

**Comment by jonschwenk** [comment]
@jsta Each netCDF file is ~250MB and there are 12*(2013-1950) files totaling 195GB. This will be smaller in compressed, Geotiff formats but it _might_ be a candidate for developing offline zonal stats due to size. GEE accounts only allow 500 GB (compressed).

**Comment by jsta** [comment]
I wonder about trying to read directly from the NOAA site without downloading (https://github.com/pangeo-data/pangeo-datastore/issues/128#issuecomment-930346337) or trying to get it added to pangeo-forge (https://pangeo-forge.readthedocs.io/en/latest/what_is_pangeo_forge.html).

**Comment by jsta** [comment]
Here's a direct link to the nc files. From what I can tell, they are suitable for pangeo-forge.

**Comment by jonschwenk** [comment]
I'm going to close this for now--ended up downloading these to Heron and setting up the scripting for local extraction.
