### ISSUE TITLE
Allow customized description (i.e. filename) for Dataset class objects

### ISSUE THREAD

**Issue by jonschwenk** [VeinsOfTheEarth/rabpro#112]
I just ran into the case where I wanted Daymet precipitation data for two different projects, with both exporting to the same GDrive folder. The default naming scheme resulted in two files with the same name in my GDrive folder. We should allow the user to either 1) specify the filename or 2) pre-pend (or append) a string to the filename. 

I think this is easy enough--just add another kwarg to accept a label when instantiating the Dataset class. Then update all the `filename=` in calls to spin up GEE tasks.

**Comment by jonschwenk** [comment]
I notice that there is the `tag` kwarg when calling main that appends a string to the GEE file exports, but I think it should be provided when specifying a dataset as each dataset is exported as a unique file.

**Comment by jsta** [comment]
Makes a lot of sense!
