### ISSUE TITLE
Some elaboration for basic example

### ISSUE THREAD

**Issue by jmdelvecchio** [VeinsOfTheEarth/rabpro#115]
Hi fam, I am trying to run basic example in a Jupyter notebook in the cloned rabpro folder and am failing. Just updated my clone from git and tried to run the basic example: 

(1) Do you need more than Level 1 Hydrosheds to run the basic example? (and maybe remind folks how to get the data they need on the basic example page) 

(2) Do you need to authenticate ee for the basic example? 

(3) In my notebook I do authenticate ee and have downloaded level 1 basins. When I ran `rabpro download hydrobasins` I noted the directory into which those files were installed and called that my environment variable in my Jupyter notebook:

`os.environ["RABPRO_DATA"] = "[me]/.local/share/rabpro"` 

However when I run 

`rpo = rabpro.profiler(coords, name='basic_test')` 

I still get 

`RuntimeError: The path you supplied appears empty.`. 

I am trying to divine my way through `utils.py` to see how `datapaths` is set but can't figure it out.

**Comment by jonschwenk** [comment]
Hey Jamster, we are working through this and hopefully will have it sorted in a day or two (or three). 

For (1), yes, you need both Level 1 and 12.

For (2), you might be right. `ee.Initialize()` is called, but not `ee.Authenticate()`. The user might need to do this before their first run of `basin_stats()`--I think once you've authenticated once, you don't need to again @jsta check me on that.

For (3), still working through that one. Everything you posted seems normal--I just tried to run the example and got the same `Runtime Error`. It is related to auto-rebuilding virtual rasters (needed for MERIT data) and something's not right, so I'm working on chasing that down.

Be warned that the repo/codebase is in heavy flux currently. I will let you know when you should be able to run things without error.

**Comment by jonschwenk** [comment]
I just pushed some commits that I hope solve (3). Re-download the repo, then try following this new example: https://github.com/VeinsOfTheEarth/rabpro/blob/main/docs/source/examples/notebooks/downloading_data.ipynb

You should only need to download HydroBasins.

Note that other example notebooks might still be broken :P

**Comment by jmdelvecchio** [comment]
Basic example working like a charm, and having great success iterating over a list of gage coordinates! 

I personally couldn't configure my proxy - I was getting a 405 error, which is either my fault or Dartmouth's fault, I imagine, as I'm using an ssh tunnel for my Jupyter notebook port on their servers. So please keep that Google Drive zip folder alive somewhere for us dummies 🙏

Thank you for all your hard work, this is just what my project needed.
