### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by thurber** [VeinsOfTheEarth/rabpro#120]
Hello `rabpro` team! I'm one of your JOSS reviewers over in https://github.com/openjournals/joss-reviews/issues/4237. I'll use this issue to keep track of all my feedback, but feel free to create separate tickets if that works best with your workflow!

- [x] the PyPI package version is behind (at 0.2.2), and there may be an issue with a circular dependency (you mention pip install is available in the first paragraph at https://veinsoftheearth.github.io/rabpro/install/index.html); conda-forge installation works!
- [x] at https://veinsoftheearth.github.io/rabpro/configure/index.html, it would be nice to mention what the default download directory will be if a user doesn't specify it with an environment variable -- that way i know if i want to change it or not! (looks like the `data_utils.download_hydrobasins()` method also allows one to specify the path, could mention that too). Update: on Mac, the default path doesn't exist and the download utility throws an error: `FileNotFoundError: [Errno 2] No such file or directory: '/Users/redacted/Library/Application Support/rabpro/HydroBasins.zip'` (similar story with `data_utils.download_merit()`
- [x] downloading with `data_utils.download_hydrobasins('./')` fails with the following message: `Downloading HydroBasins zip file (562 MB)... HydroBasins zip file was not successfully downloaded. Check proxy?` I'm not currently on a network that requires a proxy or VPN so something else must be going wrong -- let me know if you need me to provide more info about this! Update: it looks like the link you share from https://veinsoftheearth.github.io/rabpro/examples/notebooks/downloading_data.html to manually download this data is also access restricted, which may be why the method fails.
- [x] the link at https://veinsoftheearth.github.io/rabpro/configure/index.html to the merit downloads points to the Hydro data but then shows sample code for downloading the DEM data -- turns out those datasets have different user names and passwords 😅

Looks like that's as far as I can get at the moment -- let me know about the HydroBasins data (can I download from hydrosheds directly, or does the data at your google drive link have certain shape/structure that's required?), and I will pick up from here next time!

**Comment by jsta** [comment]
Thanks for the feedback @thurber. Sorry you're having trouble. 

@jonschwenk I'm not sure what's going on with the access restriction issue as it appears open to everyone:

![image](https://user-images.githubusercontent.com/7844578/158186802-67d4f645-0cab-41b8-92ec-4ca31ca30ddf.png)

**Comment by thurber** [comment]
- [ ] following along with the basic example at https://veinsoftheearth.github.io/rabpro/examples/notebooks/basic_example.html, I get the following error:
```
>>> rpo.elev_profile(dist_to_walk_km=5)
ERROR 4: /Users/thur961/im3/rabpro/MERIT_Hydro/MERIT_ELEV_HP/MERIT_ELEV_HP.vrt: No such file or directory
ERROR 4: /Users/thur961/im3/rabpro/MERIT_Hydro/MERIT_UDA/MERIT_UDA.vrt: No such file or directory
ERROR 4: /Users/thur961/im3/rabpro/MERIT_Hydro/MERIT_FDR/MERIT_FDR.vrt: No such file or directory
ERROR 4: /Users/thur961/im3/rabpro/MERIT_Hydro/MERIT_WTH/MERIT_WTH.vrt: No such file or directory
Extracting flowpath from DEM...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/core.py", line 319, in elev_profile
    self.gdf, self.flowline = ep.main(
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/elev_profile.py", line 89, in main
    cr_ds_mapped, why = mu.map_cl_pt_to_flowline(
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/merit_utils.py", line 688, in map_cl_pt_to_flowline
    cr = ru.lonlat_to_xy(lonlat[0], lonlat[1], da_obj.GetGeoTransform())
AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'
```

When I look in those directories, i see TIF files but no vrt files:
```
(rabpro) ➜  rabpro ls MERIT_Hydro/MERIT_ELEV_HP 
n30w125_elv.tif n50w125_elv.tif n55w135_elv.tif s05e155_elv.tif s10e155_elv.tif s15e155_elv.tif s20e150_elv.tif s20e175_elv.tif s25e170_elv.tif
n35w125_elv.tif n50w130_elv.tif n55w140_elv.tif s05e165_elv.tif s10e160_elv.tif s15e160_elv.tif s20e155_elv.tif s25e150_elv.tif s30e150_elv.tif
n40w125_elv.tif n50w135_elv.tif n55w145_elv.tif s05e170_elv.tif s10e165_elv.tif s15e165_elv.tif s20e160_elv.tif s25e155_elv.tif s30e165_elv.tif
n45w125_elv.tif n55w125_elv.tif n55w150_elv.tif s05e175_elv.tif s10e175_elv.tif s15e170_elv.tif s20e165_elv.tif s25e160_elv.tif
n45w130_elv.tif n55w130_elv.tif s05e150_elv.tif s10e150_elv.tif s15e150_elv.tif s15e175_elv.tif s20e170_elv.tif s25e165_elv.tif
```

**Comment by jonschwenk** [comment]
Hi @thurber , let me see if I can work through some of these issues.

1. PyPI should not be used for installing rabpro. The `pip` installation specified in the docs is only for a local install (i.e. you cloned the repo). @jsta should we just remove the PyPI version altogether so it's not accidentally installed?

2. (**A**) The [docs](https://veinsoftheearth.github.io/rabpro/configure/index.html) have been updated to demonstrate how to find the default data path `rabpro` expects. 
(**B**) If the user supplied a path that does not exist to the `download_XXX()` functions, you would indeed see that error. I added some lines to handle this case--the path will now be created if it does not exist.

4. within-Python downloading issues can be tricky to diagnose. I have expanded the error message to offer the manual download option, e.g. 
`HydroBasins zip file was not successfully downloaded. Check proxy? You may also manually download the HydroBasins file from https://drive.google.com/file/d/1NLJUEWhJ9A4y47rcGYv_jWF1Tx2nLEO9/view?usp=sharing and unzip it to C:\redacted\AppData\Local\rabpro\rabpro` 
Hopefully that helps clear things up.

5. This was a documentation error, thank you! This is confusing because there are two products: MERIT DEM and MERIT-Hydro (which includes a hydrologically-processed DEM that `rabpro` uses). It is further confusing because `rabpro` contains a download function `download_merit_dem()`, which has no use to rabpro as it needs the MERIT-Hydro (`download_merit_hydro()`) tiles. To make this clearer, I have removed the `download_merit_dem()` function, and I have updated the documentation.

I will address 5. in a separate comment.

**Comment by jonschwenk** [comment]
@thurber With respect to missing VRT files, did you manually download the tiles? The `download_merit_hydro` function should (re)build the VRTs after downloading any new tiles.

Either way, I can put a check in the `profiler` class that the VRTs are available and rebuilds them if not. Will update when that is ready.

**Comment by jsta** [comment]
Yes, I think we should remove PyPI

**Comment by thurber** [comment]
@jonschwenk, i used the `download_merit_hydro` function -- interestingly, i ran it again today and it worked, so i'm not sure what's going on there -- here's the stdout from the non-working and working times, in case that's helpful. maybe just a fluke.

non-working:
```python
>>> data_utils.download_merit_hydro('n30w150', username='redacted', password='redacted')
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/dir_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_FDR/dir_n30w150.tar'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.0M/72.0M [00:08<00:00, 8.07MB/s]
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/elv_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_ELEV_HP/elv_n30w150.tar'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 866M/866M [01:31<00:00, 9.50MB/s]
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/upa_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_UDA/upa_n30w150.tar'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 502M/502M [01:20<00:00, 6.19MB/s]
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/wth_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_WTH/wth_n30w150.tar'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.3M/25.3M [00:03<00:00, 6.89MB/s]
>>> rpo.elev_profile(dist_to_walk_km=5)
ERROR 4: /Users/redacted/rabpro/MERIT_Hydro/MERIT_ELEV_HP/MERIT_ELEV_HP.vrt: No such file or directory
ERROR 4: /Users/redacted/rabpro/MERIT_Hydro/MERIT_UDA/MERIT_UDA.vrt: No such file or directory
ERROR 4: /Users/redacted/rabpro/MERIT_Hydro/MERIT_FDR/MERIT_FDR.vrt: No such file or directory
ERROR 4: /Users/redacted/rabpro/MERIT_Hydro/MERIT_WTH/MERIT_WTH.vrt: No such file or directory
Extracting flowpath from DEM...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/core.py", line 319, in elev_profile
    self.gdf, self.flowline = ep.main(
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/elev_profile.py", line 89, in main
    cr_ds_mapped, why = mu.map_cl_pt_to_flowline(
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/merit_utils.py", line 688, in map_cl_pt_to_flowline
    cr = ru.lonlat_to_xy(lonlat[0], lonlat[1], da_obj.GetGeoTransform())
AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'
>>> 
```

working:
```python
>>> data_utils.download_merit_hydro('n30w150', username='hydrography', password='rivernetwork')
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/dir_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_FDR/dir_n30w150.tar'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.0M/72.0M [00:10<00:00, 6.95MB/s]
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/elv_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_ELEV_HP/elv_n30w150.tar'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 866M/866M [01:37<00:00, 8.92MB/s]
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/upa_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_UDA/upa_n30w150.tar'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 502M/502M [00:55<00:00, 9.00MB/s]
Downloading 'http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/distribute/v1.0/wth_n30w150.tar' into '/Users/redacted/rabpro/MERIT_Hydro/MERIT_WTH/wth_n30w150.tar'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25.3M/25.3M [00:04<00:00, 5.83MB/s]
Building flow direction virtual raster DEM from MERIT tiles...
0...10...20...30...40...50...60...70...80...90...100 - done.

Building drainage areas virtual raster DEM from MERIT tiles...
0...10...20...30...40...50...60...70...80...90...100 - done.

Building hydrologically-processed elevations virtual raster DEM from MERIT tiles...
0...10...20...30...40...50...60...70...80...90...100 - done.

Building width virtual raster from MERIT tiles...
0...10...20...30...40...50...60...70...80...90...100 - done.
>>> rpo.elev_profile(dist_to_walk_km=5)
Extracting flowpath from DEM...
>>>
```

**Comment by thurber** [comment]
- [ ] at this page https://veinsoftheearth.github.io/rabpro/examples/notebooks/multiple_basins.html, `conda install contextily` should be `conda install -c conda-forge contextily`
- [ ] in the multiple basins example (https://veinsoftheearth.github.io/rabpro/examples/notebooks/multiple_basins.html), you mention being able to skip the GCP bucket step since you provide a public asset; i think maybe the steps 5 onward assume i did not skip that step -- is it possible to test without creating the GCP assets? (my free trial is over 😿)

**Comment by jonschwenk** [comment]
Re: contextily, I have updated that notebook/doc to include `-c conda-forge`

Re: skipping the GCP bucket step--no, unfortunately you can't test it without a GCP account. However, that notebook states that `This can be done manually through the **GEE code editor** or via rabpro automation.` In fact, most users would likely want to use the GEE code editor as it is much simpler/user-friendly. The rabpro automation is really designed for more complex raster uploads (`imageCollections` rather than `images`, images with multiple bands, etc.), and is provided as a convenience more than integral functionality. That said, I can send you credentials if you'd like to use our bucket--it's free for another month :)

**Comment by thurber** [comment]
My point of confusion was thinking I could skip the step about creating my own GCP bucket -- maybe I can? In either case, I'm getting some errors relating to the interaction with `gsutil`. I have installed and initialized `gsutil`, but might certainly be missing some steps. Any ideas?

Trying to upload to my own bucket:
```python
>>> your_gee_asset = rabpro.utils.upload_gee_vector_asset(
...     zip_path, gee_user, gcp_bucket, gcp_folder="rabpro"
... )
gsutil cp basins_sl.zip tbt-rabpro-tmp/rabpro/basins_sl.zip
Traceback (most recent call last):
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/utils.py", line 944, in upload_gee_vector_asset
    subprocess.call(shell_cmd)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gsutil cp basins_sl.zip tbt-rabpro-tmp/rabpro/basins_sl.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/utils.py", line 946, in upload_gee_vector_asset
    raise RuntimeError(
RuntimeError: Errors here could indicate that gsutil is not installed.
```



Trying to use the public file:
```python
>>> your_gee_asset = 'users/jstacompute/basins_sl'
>>> 
>>> 
>>> if not os.path.exists("res.gpkg"):
...     urls, tasks = rabpro.basin_stats.compute(
...         dataset_list, gee_feature_path=your_gee_asset, folder="rabpro"
...     )
...     tag_list = ["wateroccur", "temperature_2m", "precip"]
...     data = rabpro.basin_stats.fetch_gee(urls, tag_list)
...     res = gpd.GeoDataFrame(data.merge(basins_sl, on='vote_id'))
...     res = res.set_geometry("geometry")
...     res.to_file("res.gpkg", driver="GPKG")
... else:
...     res = gpd.read_file("res.gpkg")
... 
Traceback (most recent call last):
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/ee/data.py", line 330, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/table:export?alt=json returned "Collection.loadTable: Collection asset 'users/jstacompute/basins_sl' not found.". Details: "Collection.loadTable: Collection asset 'users/jstacompute/basins_sl' not found.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/rabpro/basin_stats.py", line 397, in compute
    task.start()
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/ee/batch.py", line 89, in start
    result = data.exportTable(self._request_id, self.config)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/ee/data.py", line 1319, in exportTable
    return _prepare_and_run_export(
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/ee/data.py", line 1407, in _prepare_and_run_export
    return _execute_cloud_call(
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/ee/data.py", line 332, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: Collection.loadTable: Collection asset 'users/jstacompute/basins_sl' not found.
```

**Comment by jonschwenk** [comment]
Ah, I see. The user can (and should, probably) skip the bucket upload when working through that example. I will doubly-clarify that in the docs.

Oops, we forgot to make that asset public. Just shared it, so try again and it should work!

**Comment by thurber** [comment]
Thanks, that worked!

One more issue in this notebook:

- [ ] The method signatures for the plotting must have changed at some point, i get some errors regarding this line `legend_kwds={"label": col_label, "orientation": "horizontal", "pad": 0.01},`

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in <listcomp>
  File "<stdin>", line 5, in build_panel
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/geopandas/plotting.py", line 950, in __call__
    return plot_dataframe(data, *args, **kwargs)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/geopandas/plotting.py", line 926, in plot_dataframe
    ax.legend(patches, categories, **legend_kwds)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 305, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'label'
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in <listcomp>
  File "<stdin>", line 5, in build_panel
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/geopandas/plotting.py", line 950, in __call__
    return plot_dataframe(data, *args, **kwargs)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/geopandas/plotting.py", line 926, in plot_dataframe
    ax.legend(patches, categories, **legend_kwds)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 305, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'orientation'
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in <listcomp>
  File "<stdin>", line 5, in build_panel
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/geopandas/plotting.py", line 950, in __call__
    return plot_dataframe(data, *args, **kwargs)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/geopandas/plotting.py", line 926, in plot_dataframe
    ax.legend(patches, categories, **legend_kwds)
  File "/opt/miniconda3/envs/rabpro/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 305, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'pad'
```

**Comment by jonschwenk** [comment]
@thurber, re: 

> the manual download is working for me now, thanks! the data_utils.download_hydrobasins() is still showing the same error though

At the cost of an additional dependency, I replaced the HydroBasins download function (which used the `requests` library) with functionality provided by `pydown`, which seems to be an actively supported package. It makes the code much simpler and more robust. If you update your `rabpro` install to the repo's latest version, it should work now (unless the root problem was deeper). I, too, was getting mixed results with the original download function, but the `pydown`-based one seems to work every time.

**Comment by thurber** [comment]
thanks @jonschwenk! With the latest rabpro from main, there may be missing a missing dependency on `gdown` (although this could be from how my environment is now a mix of conda and pip...) -- just double check that.

With these updates, i'm able to get through all the examples, thanks! I'll focus on the paper itself now.

**Comment by jonschwenk** [comment]
I updated the [environment file](https://github.com/VeinsOfTheEarth/rabpro/blob/main/environment.yml) to include `gdown`, so we're all good there. Once the _JOSS_ review is complete, we'll repackage for conda-forge to incorporate all the changes for the conda installation.

**Comment by thurber** [comment]
Hi all, sorry for long delay! Reading through the paper now; great work! Here are some feedback items:
- [ ] In the figure 1 caption, a couple of the references aren't rendering correctly in the compiled paper (version i'm looking at [here](https://github.com/openjournals/joss-papers/blob/joss.04237/joss.04237/10.21105.joss.04237.pdf))
- [ ] In the Statement of Need, the reference to "Brooks (2003)" is in a different style than the rest
- [ ] Any chance there are citations already available for the ongoing rabpro work mentioned towards the end of Statement of Need? No worries if not, but sounds fascinating!
- [ ] Some inconsistencies and broken links for the citations in State of the Field

Nitpicks (up to you whether to change or not):
- [ ] "subbasin-based" is an awkward compound word (~ line 77)
- [ ] "unioning" feels awkward in this sentence (~ line 86).
- [ ] "the cleanest workflow would be" --> "the cleanest workflow is to" (~ line 92)
- [ ] "the workflow would" --> "the workflow is to" (~ line 94)
