### ISSUE TITLE
GEE catalog metadata parser is failing

### ISSUE THREAD

**Issue by jonschwenk** [VeinsOfTheEarth/rabpro#121]
Tests are failing because the parser script is writing an empty `.json` file to https://github.com/VeinsOfTheEarth/rabpro/blob/main/Data/gee_datasets.json.

It appears as if the `gee:type` tag has been removed from the Catalog metadata? Here's an example image: https://earthengine-stac.storage.googleapis.com/catalog/CPOM/catalog.json

edit: I linked to a Catalog entry. It appears that `gee:type` is still a field in the actual image metadata: https://earthengine-stac.storage.googleapis.com/catalog/CPOM/CPOM_CryoSat2_ANTARCTICA_DEM.json ...weird.

For now we can just grab an older version of the `gee_datasets.json` file and pause the Github Actions so it doesn't automatically overwrite with a blank file, but we need to figure out what's going on here.

@tzussman do you have any ideas?

**Comment by jonschwenk** [comment]
https://github.com/VeinsOfTheEarth/rabpro/commit/2102261e1549ae863f521962067575260bee1887 seems to have fixed this.

The image/imageCollection metadata files are embedded one-level deeper than before. GEE must've rearranged their catalog xml organization? Anyway, the new code finds all the assets within the asset class and loops through each one within `parse_url`. Previous behavior was one asset per url passed to `parse_url`. Now it returns a list of asset dictionaries instead of just a dictionary.

Booted up the Catalog Parser Action and will close this if everything seems fixed.

**Comment by tzussman** [comment]
yeah this change looks very reasonable to me, not sure what the catalog.json files are for but those definitely aren't the right ones to parse
