### ISSUE TITLE
Adding keyword passing to build_vrt via kwargs

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#123]
I'm about to push code adding to ability to pass arguments via kwargs to `build_vrt` from `build_virtual_rasters`. I need to have the `extents` argument exposed.

**Comment by jonschwenk** [comment]
I removed that ability in yesterday's commits because `rabpro` didn't need it, but go ahead! You can look at old versions if you want to copy the previous implementation.
