### ISSUE TITLE
force_merit doesn't actually force merit

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#124]
The `force_merit` flag doesn't do anything really. Currently the only way to force merit is to set a `da`. The current logic is to use hydrobasins unless a da is set.

**Comment by jonschwenk** [comment]
Is this true? We have

```
        # Determine method
        if self.da is None or force_hydrobasins is True:
            self.method = "hydrobasins"
            if self.da is None:
                print(
                    "Warning: no drainage area was provided. HydroBASINS will be used to delineate the basin, but result should be visually verified and coordinate updated if results are not as expected."
                )
        elif self.da <= 1000 or force_merit is True:
            self.method = "merit"
        else:
            self.method = "hydrobasins"

```
in core.py under `delineate_basin`...see https://github.com/VeinsOfTheEarth/rabpro/blob/762cdf9603b3424cea6a1e70d102e723a8445d59/rabpro/core.py#L180

**Comment by jsta** [comment]
If da is none the force_merit is True test never get evaluated.

**Comment by jonschwenk** [comment]
Yes, this is expected behavior. There is no way to use MERIT (safely) without a drainage area being provided. Hence the Warning that states HydroBASINS will be used if da == None.

**Comment by jsta** [comment]
Then I think we need a docs example showing how to get a da to force merit.

**Comment by jonschwenk** [comment]
Agree on the test, not sure that an example is needed though. It's just one extra keyword argument. Definitely should be spelled out that if da < 10000 or whatever then by default MERIT will be used; else HydroBASINS.

**Comment by jonschwenk** [comment]
https://github.com/VeinsOfTheEarth/rabpro/commit/ebe35ac18f7fa0ddc4ecbbb467ed5ac2aed30208 adds the drainage areas to the merit delineations so it's actually tested. Also added to the elevation profile test for the same reason. The checks are pretty weak, though--only looking at the object type. My reading of the merit delineation is that an empty GeoDataFrame will be returned even if the point can't be mapped, so it will pass the test (as it has been thus far)...

**Comment by jsta** [comment]
Adding a check that the GeoDataFrame is not empty.
