### ISSUE TITLE
JOSS review: Request authors to comment on test coverage

### ISSUE THREAD

**Issue by kanishkan91** [VeinsOfTheEarth/rabpro#129]
I would like the authors to comment on the test coverage. I pulled up the coverage statistics (See image below). I see that the utils files have low coverage by tests (not an issue). But some key files like the basin_stats have low coverage. Could you comment on that? I will look into some sample lines in more detail and maybe this is not an issue, but just wanted to point out. 

 
![image](https://user-images.githubusercontent.com/37234086/169709140-7e1a6988-3f5b-4824-89ef-f60a0034b7c1.png)

https://github.com/openjournals/joss-reviews/issues/4237

**Comment by jsta** [comment]
@kanishkan91 Where did you pull the coverage statistics from? I'm seeing much higher percentages in the latest CI runs:
![Screenshot 2022-05-23 102227](https://user-images.githubusercontent.com/7844578/169864191-ee6bd32f-518e-4247-95f0-e9ce56d9f979.png)

https://github.com/VeinsOfTheEarth/rabpro/runs/6530778811?check_suite_focus=true#step:8:87

**Comment by kanishkan91** [comment]
@jsta That is strange. I just pulled the stats from my local repo using `coverage`. I do see the higher coverage in the CI files. Thanks very much!

Let me look into it again.

**Comment by kanishkan91** [comment]
Also, the CI coverage looks more than adequate. So, Il go ahead and close this.
