### ISSUE TITLE
JOSS review: General documentation

### ISSUE THREAD

**Issue by kanishkan91** [VeinsOfTheEarth/rabpro#130]
- [x] Move the contribution instructions to the main readme in addition to where they are in the documentation
- [x]  Same for installation instructions
- [x]  Do the %capture (see image below) in the documentation signify anything? If not, can those be taken out?

![image](https://user-images.githubusercontent.com/37234086/169856775-43ccfe8a-7fac-4614-8d77-d27e7ab37bfe.png)

- [x] Mention the usage of rabpro.utils.coords_to_merit_tile() on the Basic example page (maybe just add it to the code example there - https://veinsoftheearth.github.io/rabpro/examples/notebooks/basic_example.html). Its an important function IMO.

https://github.com/openjournals/joss-reviews/issues/4237

**Comment by kanishkan91** [comment]
Resolved

**Comment by jsta** [comment]
The capture command is a "magic command" that hides progress printing. 
https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-capture

**Comment by kanishkan91** [comment]
> The capture command is a "magic command" that hides progress printing. https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-capture

@jsta Thanks! Did not know about that.

**Comment by jonschwenk** [comment]
Contribution instructions are now in the main readme.

Re: Moving installation instructions main readme (second check box). We discussed this and decided that we prefer the current design as it is cleaner and prevents us from updating docs in two places. 

`rabpro.utils.coords_to_merit_tile()` is now included in the Basic example.
