### ISSUE TITLE
Sri Lankan dam watersheds are too big

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#145]
Perhaps the existing watersheds are using hydrobasins and giving an unrealistic size as a result?

**Comment by jonschwenk** [comment]
? No context.

**Comment by jsta** [comment]
Rajiv says that the Sri Lankan dam watersheds in the docs are too large. I think it might be because the delineations use Hydrobasins instead of MERIT.

**Comment by jonschwenk** [comment]
Hm, well it would be easy enough to re-delineate them via MERIT. HB has an average of ~230km^2 per polygon so if they're smaller than/approximately that, then yes--definitely too small. What do you propose we do about it?

**Comment by jsta** [comment]
re-delineate with MERIT, although I think another possibility is Rajiv might be expecting incremental watersheds which is not what's showed in the docs

**Comment by jonschwenk** [comment]
Talked with Rajiv about this and am not sure everyone's on the same page here. Since it's for an example only, I vote to close this issue (perhaps adding a warning in the example that the basins were from HB and might be too large?).
