### ISSUE TITLE
basins_stats.compute fails with basins_gdf argument

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#147]
Even with a tiny polygon object, the earthengine API says:
> `ee.ee_exception.EEException: Object too large (4000000016 bytes).`

You can pass an asset path with the `gee_feature_path` argument to get around this error.

**Comment by jonschwenk** [comment]
This could have happened because I was maxxing out rabpro's GEE memory with other runs. Those have been cancelled so maybe try again? Or if you were using your personal GEE account then it's a real bug.

**Comment by jsta** [comment]
I was using my personal account.

**Comment by jsta** [comment]
This is still an error. Need to update the doc examples to reflect the work-around.

**Comment by jsta** [comment]
This appears to be specific to certain image/imagecollection assets and has nothing to do with gdf arguments

**Comment by jsta** [comment]
No errors for non-time-indexed images/collections. No errors for time-indexed assets which are "time-reduced".

Errors for time-indexed assets with no time_stats reduction.

**Comment by jsta** [comment]
## Works: 

 * all basin stats queries using a vector asset already on GEE

 * all basin stats queries using a time_stats reducer

## Doesn't work:

* uploading a feature asset on-the-fly **but only** with specific `image` raster assets

```python
# works
urls, tasks = rabpro.basin_stats.compute(
        [Dataset("projects/soilgrids-isric/soc_mean", "soc_0-5cm_mean", stats=statlist, gee_type="image")], 
    basins_gdf=gdf, validate_dataset_list=False)

# doesn't work, doesn't matter what the resolution is set at
urls, tasks = rabpro.basin_stats.compute(
        [Dataset("JRC/GSW1_3/GlobalSurfaceWater", "occurrence", stats=statlist, gee_type="image")], 
    basins_gdf=gdf, validate_dataset_list=False)
```

## Proposed fix:

Arbitrarily subject image assets to a time reducer which should have no effect other than avoiding the above error
