### ISSUE TITLE
Add proxy argument to all requests.get calls

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#40]
This would mean `utils.get_datapaths` and all functions that call get_datapaths.

**Comment by jsta** [comment]
Seems like this can be set once at the Session level (not at each individual function call): https://stackoverflow.com/a/5620590

**Comment by jsta** [comment]
For whatever reason, this doesn't seem to be an issue for me anymore.

**Comment by jsta** [comment]
Having this problem again after switching to a different machine.

**Comment by jonschwenk** [comment]
At least on Windows, I found that setting the environment variables 'http_proxy' and 'https_proxy' was sufficient.
