### ISSUE TITLE
Remove OpenCV dependency

### ISSUE THREAD

**Issue by tzussman** [VeinsOfTheEarth/rabpro#50]
See #48

Only one OpenCV function is used (findContours) in `regionprops()` in utils.py. If the [skimage equivalent](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.find_contours) has the same behavior, use that instead. I think the function is currently optimized for OpenCV, so something like [this](https://stackoverflow.com/questions/66704830/how-to-use-skimage-contours-in-opencv) could work, but long-term it'd be better to rewrite this for skimage.

**Comment by jsta** [comment]
The opencv installation process is **such** a headache.

**Comment by jonschwenk** [comment]
Unfortunately the skimage find_contours is not a drop-in replacement for OpenCV's. However, I was able to implement skimage's contours and reproduce the ~same result as OpenCV. The only differences I saw were that the returned perimeter coordinates have a different starting pixel, and skimage was going counter-clockwise in the perimeter trace. (The clockwise-ness is controllable, I just didn't think it made a difference). The commit above removes OpenCV only from utils.py--wanted to doublecheck that the tests passed via GH Actions before removing OpenCV as a dependency in the env file. (Tests passed on my machine.)

**Comment by jonschwenk** [comment]
If tests pass, can @jsta  remove the dependency officially? I already deleted the import statement.

**Comment by jonschwenk** [comment]
The only thing I am not sure about here is if there are holes in the blobs. This might return multiple contours (e.g. outer ring and then the ring of the hole)--in those cases an error will be raised since I check that there is only one contour returned.

**Comment by jsta** [comment]
It turns out the opencv build error I referenced was fixed upstream. So if skimage replacement doesn't work we can roll back if necessary.

**Comment by jsta** [comment]
We can't rely on the current tests because none of them use the contours functionality because none of them use merit.

**Comment by jonschwenk** [comment]
I just pushed a commit that takes care of the holes. Only the largest perimeter is returned. So I think this is safe now.

![image](https://user-images.githubusercontent.com/14874485/169590866-bd556893-1d4b-4d41-8944-f48e8e026942.png)
