### ISSUE TITLE
Unpin geopandas dependency

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#53]
See https://github.com/jonschwenk/RivGraph/pull/60

**Comment by tzussman** [comment]
Right now we have it as >=0.7.0, which is somewhat arbitrary, but much better than the old =0.7.0 pin.
Given VeinsOfTheEarth/VotE#49, should we pin PyProj instead?

**Comment by jonschwenk** [comment]
I think so re: pinning to PyProj.
