### ISSUE TITLE
Design method for tracking and including user-added datasets

### ISSUE THREAD

**Issue by jonschwenk** [VeinsOfTheEarth/rabpro#54]
When users add their own datasets (images/imagecollections) to GEE, they will also need to incorporate the metadata information somehow so rabpro has what it needs to compute statistics. It's not clear to me how this is supposed to happen (perhaps it's already designed?), but we should have a clear procedure. For datasets that we (rabpro developers) make public, these could be included in the fetched metadata file so that all users would have access to them (i.e. not just on our local machines).

**Comment by jsta** [comment]
One option would be to have a user-edited file in this repository that gets validated and merged with the autogenerated file from GEE

**Comment by tzussman** [comment]
This functionality exists, and is basically what Jem described - there's a local user-edited file that rabpro reads and merges with the default catalog json file. I have a draft documentation paragraph about this and started making an example notebook for this - will make a PR once it's done, and can close this once that's merged

**Comment by jonschwenk** [comment]
I would like to test it by adding a dataset, and we still need guidelines for how to add multi-banded rasters. I'll upload a single- and multi-band for testing.

**Comment by jonschwenk** [comment]
We need to make clear documentation for this process.

**Comment by jsta** [comment]
Currently, rabpro looks for a file with asset data at `Path(appdirs.user_config_dir("rabpro", "rabpro"), "user_gee_datasets.json")`

**Comment by jsta** [comment]
I'm about to push a commit that enables pulling from a user contributed GEE asset where `user_gee_datasets.json` looks like:

```json
[
    {
        "id": "projects/sat-io/open-datasets/Geomorpho90m/slope",
        "name": "Geomorpho90m: Slope",
        "start_date": null,
        "end_date": null,
        "type": "image_collection",
        "bands": {
            "None": {
                "resolution":90
            }
        }
    }
]
```

**Comment by jsta** [comment]
Documented at https://jonschwenk.github.io/rabpro/data/index.html#user-dataset-configuration

**Comment by jonschwenk** [comment]
There is no way to specif

**Comment by jsta** [comment]
I've stashed my example `user_gee_datasets.json` in `rabpro/Data`. Seems like a good plan would be to open issues against that file for coordinated tracking. Could write this file to the expected location on installation...

**Comment by jonschwenk** [comment]
Could we just use the same path as for the auto-downloaded GEE json? I'm still kind of dumb about those things, but we've already had to deal with the path issue so maybe can reuse that solution?

**Comment by jsta** [comment]
Yes we should re-use the code for the GEE json.

**Comment by jsta** [comment]
I think I'll change [this line](https://github.com/VeinsOfTheEarth/rabpro/blob/main/rabpro/data_utils.py#L58) to copy over `Data/user_gee_datasets.json` to the appdirs location if no file exists there.

**Comment by jsta** [comment]
As far as I can tell setting the units (band info) and the citation field on an image(collection) asset requires a complicated manifest uploading process. https://developers.google.com/earth-engine/guides/image_manifest

**Comment by jonschwenk** [comment]
I think it's ok if we don't specifically set those fields as long as the units/citation info is somewhere in the metadata or description. It just needs to be available--I'm less concerned about where it shows up.

Do any of the links/packages I sent via slack not do some of this automatically? That would be nice.

**Comment by jsta** [comment]
@jonschwenk What are your thoughts about the template form I set up? https://github.com/VeinsOfTheEarth/rabpro/issues/new?assignees=&labels=data+request&template=data-request.yml

**Comment by jsta** [comment]
https://github.com/samapriya/Planet-GEE-Pipeline-CLI does uploading by manifest but the installation and setup of that tool looks so complicated (not even sure it works with non-Planet data). Might be more complicated than just writing a simple manifest tool ourselves.

**Comment by jonschwenk** [comment]
> @jonschwenk What are your thoughts about the template form I set up? https://github.com/VeinsOfTheEarth/rabpro/issues/new?assignees=&labels=data+request&template=data-request.yml

I think the template looks nice. Do we want to make the projection required? I guess it's easy enough for us to read it... I assume having gone through the full process now once or twice that the template will provide all the required info? What about nodata value?

**Comment by jonschwenk** [comment]
> https://github.com/samapriya/Planet-GEE-Pipeline-CLI does uploading by manifest but the installation and setup of that tool looks so complicated (not even sure it works with non-Planet data). Might be more complicated than just writing a simple manifest tool ourselves.
> 
> https://github.com/samapriya/geeup does uploading by manifest but it seems the manifest "metadata" is only what is pulled automatically from `gdalinfo`, probably no band units or citation info.

Ok, well again, I don't really care how the units or citation info is made available, just that it is. So if it's easy to put it in the description upon upload, let's just go that route.

**Comment by jsta** [comment]
Done
![image](https://user-images.githubusercontent.com/7844578/150400439-0c486ddc-9cdb-4004-8e8b-3c6f636f401c.png)

**Comment by jonschwenk** [comment]
Ooo that's nice  🤩

**Comment by jonschwenk** [comment]
How do we add external-to-rabpro user datasets to the User Datasets? Like other Geomorpho90m products?

**Comment by jsta** [comment]
Add an entry to https://github.com/VeinsOfTheEarth/rabpro/blob/main/Data/user_gee_datasets.json
