### ISSUE TITLE
elev_profile error

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#63]
Running this formerly working snippet:

```python
import geopandas as gpd
import rabpro
from rabpro import utils
from rabpro.subbasin_stats import Dataset

coords_file = gpd.read_file(r"tests/data/Big Blue River.geojson")
rpo = rabpro.profiler(coords_file)
rpo.delineate_basins()
rpo.elev_profile()
```

Gives an error:

> UnboundLocalError: local variable 'flowpath' referenced before assignment

**Comment by jsta** [comment]
This seems to be cause by the fact that all of the "centerline" code has been commented out...

**Comment by jonschwenk** [comment]
Oh yeah, I made a decision with @tzussman that we would roll back the support for along-centerline calculations in favor of a point. So as of now, centerlines are not supported. Workaround is to use the downstream-most point of the centerline as your initial (lon, lat).

**Comment by jonschwenk** [comment]
Centerline made less sense when working with MERIT data as the concept of incremental catchments (i.e. drainage area added as you move downstream) would be at a pixel-scale. Could supply a threshold for when to delineate another incremental catchment, but the functionality seemed to get very limited use thus far. The "new" approach would have the user RaBPro all the points along the centerline at whatever intervals they wanted, then use polygon differencing to find the incremental ones. But we left the code there in the event that we start seeing more use cases.

**Comment by jsta** [comment]
Does it make sense to remove elev_profile from the example workflow and tests?

**Comment by jonschwenk** [comment]
Maybe, although I _thought_ if a centerline was provided, we just initialized as a point...at least that would be easy enough. But if the test is on the centerline, probably just turn it off for now.

**Comment by jsta** [comment]
The example code I posted doesn't do anything to specify a centerline. Seems like something in either `profiler` or `delineate_basins` is producing a centerline causing this error further in the pipeline.

**Comment by jonschwenk** [comment]
I think `Big Blue River.geojson `is read as a centerline even though it might be a collection of Point types.

**Comment by jonschwenk** [comment]
elev_profile() works as expected if the input is a coordinate. I think this is a documentation issue; we don't support centerlines anymore.

**Comment by jsta** [comment]
> Maybe, although I thought if a centerline was provided, we just initialized as a point...at least that would be easy enough. But if the test is on the centerline, probably just turn it off for now.

Not as far as I can tell. Would the procedure be to pick the centerline point with the largest DA?

**Comment by jsta** [comment]
I'm not sure how to fix this the "right" way. Do we remove all mention of centerlines from **all** the docs? Centerlines currently run without error in the `delineate_basins` operation. 

In the meantime, I'm adding a more informative error when attempting to `elev_profile` a centerline:
```python
intype = "centerline"  # deprecated
raise DeprecationWarning(
    "elev_profile only supports single 'point' coordinate pairs, not multipoint 'centerlines"
)
```

**Comment by jonschwenk** [comment]
I think we just don't mention centerlines, but leave the functionality there.
