### ISSUE TITLE
ObuPermafrostProbabilityv5

### ISSUE THREAD

**Issue by jcrowland70** [VeinsOfTheEarth/rabpro#92]
## description 
Northern Hemisphere modeled permafrost probabilities. 
Obu, Jaroslav; Westermann, Sebastian; Kääb, Andreas; Bartsch, Annett (2018): Ground Temperature Map, 2000-2016, Northern Hemisphere Permafrost. Alfred Wegener Institute, Helmholtz Centre for Polar and Marine Research, Bremerhaven, PANGAEA, https://doi.org/10.1594/PANGAEA.888600
The product provides modeled mean annual ground temperatures (MAGT) at the top of the permafrost for the Northern Hemisphere at 1 km spatial resolution. Permafrost probability (fraction values from 0 to 1) is assigned to each grid cell with MAGT < 0°C. Based on its permafrost probability each grid cell is classified as continuous, discontinuous and sporadic permafrost. The processing extent covers exposed land areas of the Northern Hemisphere down to 25 ° latitude. The mean MAGT was validated with GTN-P and TSP borehole ground temperature data and yielded a RMS of 2.0 °C. According to the results, permafrost (MAGT < 0 °C) covers 15 % of exposed land of the Northern Hemisphere.

## source
(https://doi.pangaea.de/10.1594/PANGAEA.888600?format=html#download)
01/05/2022

## units
Permafrost probability (fraction values from 0 to 1) is assigned to each grid cell with MAGT < 0°C.

## other metadata
2000-2016

## location
/Volumes/TheRiver/RaBPro/ObuPermafrost/UiO_PEX_PERPROB_5.0_20181128_2000_2016_NH.zip
https://store.pangaea.de/Publications/ObuJ-etal_2018/UiO_PEX_PERPROB_5.0_20181128_2000_2016_NH.zip

-----

* [x] uploaded to GEE
* [x] metadata/description filled
* [x] tested integration with `rabpro`

**Comment by jsta** [comment]
Uploaded, logged, and verified to work with subbasin stats using a Dataset call like:

```python
Dataset(
            "users/jstacompute/UiO_PEX_PERPROB_5p0_20181128_2000_2016_NH",
            "b1",
        )
```
