### ISSUE TITLE
Hydrobasins downloading utilities don't include level 12

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#95]
They only download level 1 data...

**Comment by jonschwenk** [comment]
Seems like an easy-enough addition...I'm tempted just to point users to the Hydrobasins download page and the data storage structure rabpro expects and not really support these download functions...

**Comment by jsta** [comment]
I put the infrastructure in place, imo if we don't support level 12 downloads we should make force_merit=True the default.

**Comment by jsta** [comment]
Seems like this might be technically resolved with the zip downloading capabilities. Still need to mention level 12 in the website docs then.

**Comment by jonschwenk** [comment]
Yep, the zip file contains both Levels. It's still a little messy and needs a review/cleanup for consistency but I believe it should work fine. I didn't test the `proxy` arg.
